
Interface-Graphique-Java:
  - src/main/java/projetS3Voyageur/Interface/*

Back-end:
  - src/main/*

test:
  - src/test/*
  
Algorithme-de-recherche:
  - src/main/java/projetS3Voyageur/ModesDeRecherches/*
  
Statistique:
  - Statistiques/*
  
Interaction-Java/BD:
  - src/main/java/projetS3Voyageur/bd/*
