
Interface-Graphique-Java:
  - src/main/java/projetS3Voyageur/Interface/*

Back-end:
  - src/main/*

test:
  - src/test/*
  
Algorithme-de-recherche:
  - src/main/java/projetS3Voyageur/ModesDeRecherches/*

Algorithme arbre minimum recouvrant:
  - src/main/java/projetS3Voyageur/ModesDeRecherches/acm

Statistique:
  - Statistiques/*
